services:

  app:
    container_name: your-django-app-name
    image: django-app
    build:
      context: .
      dockerfile: .devcontainer/app/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./app:/workspaces
      - ./app/static:/workspaces/static
    tty: true
    expose:
      - 8080
    ports:
      - "8000:8000"
    environment:
      - CONTAINER=Django-app
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
    develop:
      watch:
        - action: sync
          path: ./app
          target: /workspaces
          ignore:
            - "**/node_modules/**"
            - "**/__pycache__/**"
        - action: rebuild
          path:  ./app/requirements.txt
        - action: rebuild
          path:  ./app/package.json
        - action: rebuild
          path:  docker-compose.yml
        - action: rebuild
          path:  .env
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    # command: sh -c "/opt/entrypoint.sh"

  web:
    container_name: your-django-web-name
    image: django-web
    build:
      context: .
      dockerfile: .devcontainer/web/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./app/static:/workspaces/static
    tty: true
    ports:
      - "80:80"
    environment:
      - CONTAINER=Django-web
      - DEBUG=${DEBUG}
    develop:
      watch:
        - action: rebuild
          path:  docker-compose.yml
        - action: rebuild
          path:  .env
    networks:
      - frontend
    depends_on:
      - app
    command: sh -c "/opt/entrypoint.sh"

  db:
    container_name: your-django-db-name
    image: django-db
    build:
      context: .
      dockerfile: .devcontainer/db/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./db:/workspaces
    tty: true
    environment:
      - CONTAINER=Django-db
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
      - POSTGRE_VERSION={POSTGRE_VERSION}
    develop:
      watch:
        - action: rebuild
          path:  docker-compose.yml
        - action: rebuild
          path:  .env
    networks:
      - backend
    command: sh -c "/opt/entrypoint.sh"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  frontend:
    name: frontend
  backend:
    name: backend
